spring.application.name=electroshop

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/electroshop?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}

server.port=8080
spring.web.resources.static-locations=${UPLOAD_STATIC_LOCATIONS:file:uploads/}
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB

# =========================
# VNPAY SANDBOX
# =========================

vnpay.version=2.1.0
vnpay.command=pay
vnpay.tmn-code=${VNPAY_TMN_CODE:}
vnpay.hash-secret=${VNPAY_HASH_SECRET:}

vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html

vnpay.currency=VND
vnpay.locale=vn
vnpay.order-type=other

# Địa chỉ HTTPS ngrok của backend
app.public-base-url=${PUBLIC_BASE_URL:http://localhost:8080}

# Địa chỉ frontend React
app.frontend-url=${FRONTEND_URL:http://localhost:5173}
